Repository anasuryana/wms_ci3, pull requests merged in 2025-05, with the labels that each got.

#454 fix : update line code
  application/views/wms/vser_fg_wip.php
Labels: help wanted

#455 fix : tambah line hw
  application/views/wms/vkeikaku.php
  application/views/wms/vkeikaku_fullpage.php
Labels: help wanted

#456 fix : metode input output WIP
  application/views/manufacture/output_wip.php
Labels: invalid

#457 fix : output wip
  application/views/manufacture/output_wip.php
Labels: bug

#458 Dev 20250505
  README.md
  application/views/manufacture/output_wip.php
Labels: bug, documentation

#460 feat : tampilkan CT A CT B
  application/views/wms/vkeikaku.php
  application/views/wms/vkeikaku_fullpage.php
Labels: enhancement

#462 fix : alternatif ketika gagal dapatkan data kalkulasi
  application/views/wms/vkeikaku.php
  application/views/wms/vkeikaku_fullpage.php
Labels: bug

#464 fix : outstanding scan result
  application/views/wms_report/outstanding_scan_tracer.php
Labels: invalid

#465 fix : nilai efficiency
  application/views/wms/vkeikaku.php
  application/views/wms/vkeikaku_fullpage.php
Labels: bug

#466 feat : munculkan model list per line
  application/views/wms/vkeikaku.php
  application/views/wms/vkeikaku_fullpage.php
Labels: enhancement

#467 feat : input sequence di process master
  application/views/wms/vitem_process_master.php
Labels: enhancement

#468 fix : ui ux
  application/views/wms/vkeikaku.php
  application/views/wms/vkeikaku_fullpage.php
Labels: enhancement

#469 fix : ketika REV-RET juga ganti qty label
  application/controllers/RETPRD.php
  application/models/Raw_material_labels_mod.php
Labels: invalid

#470 fix : khusus BT3 & BT4 report graph
  application/views/wms/vkeikaku.php
  application/views/wms/vkeikaku_fullpage.php
Labels: enhancement

#471 fix : keikaku BT3 BT4 seperti MC
  application/views/wms/vkeikaku.php
  application/views/wms/vkeikaku_fullpage.php
Labels: enhancement

#472 feat : munculkan status asset
  application/controllers/RCV.php
  application/models/PO_mod.php
  application/views/wms/vrcv_customs.php
Labels: enhancement

#473 chore : update datatable
  assets/DataTables/datatables.css
  assets/DataTables/datatables.js
  assets/DataTables/datatables.min.css
  assets/DataTables/datatables.min.js
Labels: upgrade dependencies

#474 fix : tidak bisa pilih column
  application/views/wms/vrcv_customs.php
Labels: bug

#475 feat : edit sequence
  application/views/wms/vitem_process_master.php
Labels: enhancement

#477 feat : munculkan department
  application/controllers/RCV.php
  application/models/RCV_mod.php
  application/views/wms/vrcv_customs.php
Labels: enhancement
