Repository anasuryana/wms_ci3, pull requests merged in 2025-07, with the labels that each got.

#494 fix : kalkulasi tidak terhapus
  application/controllers/SER.php
Labels: enhancement

#495 feat : add validation before save calculation
  application/views/wms/vkeikaku.php
  application/views/wms/vkeikaku_fullpage.php
Labels: enhancement

#496 fix : info no data
  application/views/wms/vsimvsstock.php
Labels: enhancement

#497 fix : include assy code info
  application/views/wms/vkeikaku.php
  application/views/wms/vkeikaku_fullpage.php
Labels: enhancement

#499 fix : notif masih muncul harusnya hilang
  application/views/wms/vkeikaku.php
  application/views/wms/vkeikaku_fullpage.php
Labels: bug

#500 feat : to inform user about some item of SI disappear
  application/views/wms/vdelv.php
Labels: enhancement

#502 chore : upgrade datatable
  assets/DataTables/datatables.css
  assets/DataTables/datatables.js
  assets/DataTables/datatables.min.css
  assets/DataTables/datatables.min.js
Labels: upgrade dependencies

#503 fix : gagal simpan revisi return ke ITH
  application/controllers/RETPRD.php
Labels: bug

#505 feat : ganti komponen combobox
  application/views/wms/vfg_ret_inc.php
Labels: enhancement

#508 feat : auto load prodplan ketika ada di tab prodplan
  application/views/wms/vkeikaku.php
  application/views/wms/vkeikaku_fullpage.php
Labels: enhancement

#509 fix : tambah department accounting
  application/controllers/MSTLOC.php
Labels: enhancement

#512 refactor : hapus menu tidak dipakai lagi
  application/controllers/SPL.php
  application/views/wms_report/vrpt_cims_vs_psn.php
Labels: refactor

#513 feat : based on attorney
  application/controllers/PO.php
Labels: enhancement

#515 feat : tampilkan file yang tidak valid
  application/views/wms/v_upload_pl.php
Labels: enhancement

#519 feat : ganti component contextmenu di menu return RC
  application/views/wms/vincomingfg_rtn_rc.php
Labels: help wanted

#523 feat : ganti component contextmenu di menu multilayer FG
  application/views/wms/vincomingfg_multilayer.php
Labels: help wanted

#525 feat : cegah join beda lokasi
  application/views/wms/vcombinelabel2.php
Labels: enhancement

#526 feat : cegah join beda job jika lokasi selain AFWH3
  application/views/wms/vcombinelabel2.php
Labels: enhancement
